# Generated by Django 2.0.5 on 2018-05-14 09:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('asset_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
